### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by homecoder** [yadizhou/DynaUI#1]
Hi There,

I was puttering around looking for some modules for wxPython, and I stumbled onto this project.

I've downloaded the demo and I loved what I saw, however, the demo itself contains so many assets its difficult to discern what the individual components are doing.

Could you direct me to some documentation?

**Comment by yadizhou** [comment]
Hi homecoder, I have no plan to write the document due to limited time. However, I will answer any specific question if you have. In addition, DynaUI.demo.demo.py is a collection of most of the features. If you know how wxPython works, the demo should help you a lot.
Sorry for not being able to provide the documentation.
Thank you.
